name: Task
title: "Task Name"
description: "Low-level unit of work, usually corresponding to a pull request"
labels: Task
body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: "Provide a brief overview of the epic and its goals. Include any relevant background information or context."
  validations:
    required: true
- id: dependencies
  type: textarea
  attributes:
    label: Dependencies
    placeholder: |
      - [ ] Link to issue required to be completed before this task be started
- id: acceptanceCriteria
  type: textarea
  attributes:
    label: Acceptance Criteria
    placeholder: |
      - _List of high-level system behaviors or conditions that need to be met for this epic to be considered finished_
  validations:
    required: true
- id: relatedIssues
  type: textarea
  attributes:
    label: Related Issues
    placeholder: |
      - _List of epics or tasks that are worth mentioning in the context of this issue_
