name: Task
title: "Task Name"
description: "Low-level unit of work, usually corresponding to a pull request"
labels: [Task]
body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: "Provide a brief overview of the task and its goals. Include any relevant background information or context."
  validations:
    required: true
- id: acceptanceCriteria
  type: textarea
  attributes:
    label: Acceptance Criteria
    placeholder: |
      - _List of detailed behaviors or conditions that must be met for this issue to be closed_
  validations:
    required: true
- id: dependencies
  type: textarea
  attributes:
    label: Dependencies
    placeholder: |
      - [ ] Link to issue required to be completed before this issue can be started
- id: relatedIssues
  type: textarea
  attributes:
    label: Related Issues
    placeholder: |
      - _List of epics or tasks that are worth mentioning in the context of this issue_
