import { AppRoot } from './(components)/root';
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  return (
    <html lang={params.locale}>
      <body>
        <AppRoot>{children}</AppRoot>
      </body>
    </html>
  );
}
